const fs = require("fs");
const path = require("path");
const { renderHomePage } = require("../site-src/templates/home");
const { renderDocsPage } = require("../site-src/templates/docs");

const root = path.resolve(__dirname, "..");

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8").trim() + "\n";
}

function write(relativePath, content) {
  fs.writeFileSync(path.join(root, relativePath), content);
  console.log(`Built ${relativePath}`);
}

const homeExtraHead = read("site-src/content/home/extra-head.html");
const homeMain = read("site-src/content/home/main.html");
const purchasingExtraHead = read("site-src/content/inventory-purchasing/extra-head.html");
const purchasingMain = read("site-src/content/inventory-purchasing/main.html");

const pages = [
  {
    output: "index.html",
    render: renderHomePage,
    props: {
      title: "SmartPrints - Solution for Fast-Food, Restaurant, coffee shop ... in Saudi Arabia.",
      description: "SmartPrints Functionnal Documentation For Cloud POS Solution",
      lang: "en",
      dir: "ltr",
      dataLangEn: "index.html",
      dataLangAr: "index-ar.html",
      homeHref: "index.html",
      extraHead: homeExtraHead,
      mainHtml: homeMain,
    },
  },
  {
    output: "index-ar.html",
    render: renderHomePage,
    props: {
      title: "SmartPrints - Solution for Fast-Food, Restaurant, coffee shop ... in Saudi Arabia.",
      description: "SmartPrints Functionnal Documentation For Cloud POS Solution",
      lang: "ar",
      dir: "rtl",
      dataLangEn: "index.html",
      dataLangAr: "index-ar.html",
      homeHref: "index-ar.html",
      extraHead: homeExtraHead,
      mainHtml: homeMain,
    },
  },
  {
    output: "inventory-purchasing.html",
    render: renderDocsPage,
    props: {
      title: "SmartPrints - Inventory: Purchasing",
      description: "SmartPrints Inventory Documentation - Inventory: Purchasing",
      lang: "en",
      dir: "ltr",
      dataLangEn: "inventory-purchasing.html",
      dataLangAr: "inventory-purchasing-ar.html",
      homeHref: "index.html",
      extraHead: purchasingExtraHead,
      mainHtml: purchasingMain,
    },
  },
  {
    output: "inventory-purchasing-ar.html",
    render: renderDocsPage,
    props: {
      title: "SmartPrints - Inventory: Purchasing",
      description: "SmartPrints Inventory Documentation - Inventory: Purchasing",
      lang: "ar",
      dir: "rtl",
      dataLangEn: "inventory-purchasing.html",
      dataLangAr: "inventory-purchasing-ar.html",
      homeHref: "index-ar.html",
      extraHead: purchasingExtraHead,
      mainHtml: purchasingMain,
    },
  },
];

for (const page of pages) {
  const output = `<!-- Generated by scripts/build-site.js. Edit site-src instead. -->\n${page.render(page.props)}`;
  write(page.output, output);
}
