const fs = require("fs");
const path = require("path");
const { renderHomePage } = require("../site-src/templates/home");
const { renderDocsPage } = require("../site-src/templates/docs");

const root = path.resolve(__dirname, "..");

const KNOWN_AR_PAGES = new Set([
  "index-ar.html",
  "getting-started-ar.html",
  "cloud-pos-ar.html",
  "cloud-administration-ar.html",
  "smart-kiosk-ar.html",
  "smart-menu-ar.html",
  "smart-kitchen-app-ar.html",
  "smart-whatsapp-ar.html",
  "smart-waiter-ar.html",
  "inventory-intro0-ar.html",
  "inventory-intro-ar.html",
  "inventory-ingredients-ar.html",
  "inventory-suppliers-recipies-ar.html",
  "inventory-live-ar.html",
  "inventory-purchasing-ar.html",
  "inventory-stock-control-ar.html",
  "inventory-transfers-preparation-ar.html",
  "inventory-reports-ar.html",
]);

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8").trim() + "\n";
}

function write(relativePath, content) {
  fs.writeFileSync(path.join(root, relativePath), content);
  console.log(`Built ${relativePath}`);
}

function toArabicHref(href) {
  if (!href || href.startsWith("#")) {
    return href;
  }

  if (/^(https?:|mailto:|tel:|javascript:)/i.test(href)) {
    return href;
  }

  const hashIndex = href.indexOf("#");
  const pathPart = hashIndex === -1 ? href : href.slice(0, hashIndex);
  const hashPart = hashIndex === -1 ? "" : href.slice(hashIndex);
  const fileName = pathPart.split("/").pop() || "";

  if (!fileName.endsWith(".html") || fileName.endsWith("-ar.html")) {
    return href;
  }

  const arabicCandidate = fileName.replace(/\.html$/i, "-ar.html");
  if (!KNOWN_AR_PAGES.has(arabicCandidate)) {
    return href;
  }

  const directory = pathPart.slice(0, pathPart.length - fileName.length);
  return `${directory}${arabicCandidate}${hashPart}`;
}

function rewriteHtmlLinksForLang(html, lang) {
  if (lang !== "ar") {
    return html;
  }

  return html.replace(/href=(["'])([^"']*)\1/gi, (match, quote, href) => {
    return `href=${quote}${toArabicHref(href)}${quote}`;
  });
}

const homeExtraHead = read("site-src/content/home/extra-head.html");
const homeMain = read("site-src/content/home/main.html");
const purchasingExtraHead = read("site-src/content/inventory-purchasing/extra-head.html");
const purchasingMain = read("site-src/content/inventory-purchasing/main.html");

const pages = [
  {
    output: "index.html",
    render: renderHomePage,
    props: {
      title: "SmartPrints - Solution for Fast-Food, Restaurant, coffee shop ... in Saudi Arabia.",
      description: "SmartPrints Functionnal Documentation For Cloud POS Solution",
      lang: "en",
      dir: "ltr",
      dataLangEn: "index.html",
      dataLangAr: "index-ar.html",
      homeHref: "index.html",
      extraHead: homeExtraHead,
      mainHtml: homeMain,
    },
  },
  {
    output: "index-ar.html",
    render: renderHomePage,
    props: {
      title: "SmartPrints - Solution for Fast-Food, Restaurant, coffee shop ... in Saudi Arabia.",
      description: "SmartPrints Functionnal Documentation For Cloud POS Solution",
      lang: "ar",
      dir: "rtl",
      dataLangEn: "index.html",
      dataLangAr: "index-ar.html",
      homeHref: "index-ar.html",
      extraHead: homeExtraHead,
      mainHtml: homeMain,
    },
  },
  {
    output: "inventory-purchasing.html",
    render: renderDocsPage,
    props: {
      title: "SmartPrints - Inventory: Purchasing",
      description: "SmartPrints Inventory Documentation - Inventory: Purchasing",
      lang: "en",
      dir: "ltr",
      dataLangEn: "inventory-purchasing.html",
      dataLangAr: "inventory-purchasing-ar.html",
      homeHref: "index.html",
      extraHead: purchasingExtraHead,
      mainHtml: purchasingMain,
    },
  },
  {
    output: "inventory-purchasing-ar.html",
    render: renderDocsPage,
    props: {
      title: "SmartPrints - Inventory: Purchasing",
      description: "SmartPrints Inventory Documentation - Inventory: Purchasing",
      lang: "ar",
      dir: "rtl",
      dataLangEn: "inventory-purchasing.html",
      dataLangAr: "inventory-purchasing-ar.html",
      homeHref: "index-ar.html",
      extraHead: purchasingExtraHead,
      mainHtml: purchasingMain,
    },
  },
];

for (const page of pages) {
  const props = {
    ...page.props,
    mainHtml: rewriteHtmlLinksForLang(page.props.mainHtml, page.props.lang),
  };
  const output = `<!-- Generated by scripts/build-site.js. Edit site-src instead. -->\n${page.render(props)}`;
  write(page.output, output);
}
